name: VGM Player Build and Package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the develop branch
  # push:
  #   branches: [ develop ]
  # pull_request:
  #   branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}  
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: Linux-x64
    steps:

      # ==== VGM Player git repo  ====
      - name: Check out VGM Player repo
        uses: actions/checkout@v4
        with:
          path: VGM_Player
          submodules: false

      # ==== OS Specific Dependencies and GBDK package ====
      # Decompress the gbdk contents into VGM_Player/gbdk
      # Remove git repo files
      - name: Linux Depends
        if: matrix.name == 'Linux-x64'
        run: |
          cd VGM_Player
          curl -Lo gbdk.tar.gz https://github.com/gbdk-2020/gbdk-2020/releases/download/pre-release/gbdk-linux64.tar.gz
          tar xvfz gbdk.tar.gz
          rm -f gbdk.tar.gz
          python -m pip install --upgrade Pillow
          python -m pip install --upgrade wave
          rm -rf .git .gitignore .github
          cd ..

      # ==== Pre-Build: Set environment vars ====
      # Needs to be in a separate step than build so that setting the environment var takes effect
      #
      - name: Pre-Build Linux/MacOS
        if: (matrix.name == 'Linux-x64')
        shell: bash
        run: |
          echo "BUILD_PACKAGE_FILENAME=${{ matrix.name }}.tar.gz" >> $GITHUB_ENV

      # ==== Builds ====
      - name: Build VGM Player Linux
        if: (matrix.name == 'Linux-x64')
        shell: bash
        run: |
          cd VGM_player/
          make
          cd ..

      # ==== Packaging ====
      - name: Package build Linux/MacOS
        if: (matrix.name == 'Linux-x64')
        shell: bash
        run: |
          mkdir package
          tar czf package/${{ env.BUILD_PACKAGE_FILENAME }} VGM_player/build

      - name: Store build
        if: (matrix.name == 'Linux-x64')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }} build
          path: package/${{ env.BUILD_PACKAGE_FILENAME }}
          # retention-days: 14
